deployment:
  replicas: 2
  imageVersion: IMAGE_VERSION
  imageURL: 655431895664.dkr.ecr.us-east-1.amazonaws.com/roboshop/dev/frontend
hpa:
  cpuUtilization: 15
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:655431895664:targetgroup/roboshop-dev/0a66f17ca797691c
